knp_gaufrette:
  stream_wrapper: ~

  adapters:
    product_adapter:
      local:
        directory: "%kernel.project_dir%/public/modules/documents"

  filesystems:
    document_fs:
      adapter: product_adapter

vich_uploader:
  db_driver: orm
  storage: gaufrette

  metadata:
    type: attribute

  mappings:
    documents:
      uri_prefix: /modules/documents
      upload_destination: document_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

when@test:
  knp_gaufrette:
    adapters:
      product_adapter:
        local:
          directory: "%kernel.cache_dir%/modules/documents"
