vich_uploader:
  db_driver: orm

  mappings:
    documents:
      uri_prefix: /documents/modules
      upload_destination: "%kernel.project_dir%/public/documents/modules"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
